# This file was generated by GoReleaser. DO NOT EDIT.
class Aoj < Formula
  desc "A command-line tool for Aizu Online Judge (AOJ)"
  homepage "https://github.com/travelist/aoj-cli"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/travelist/aoj-cli/releases/download/v0.5.0/aoj-cli_0.5.0_macOS_amd64.tar.gz"
    sha256 "73ded0a4bbff5c226d8695226980f9bf6f667267b918cfd7d2af94503822d091"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/travelist/aoj-cli/releases/download/v0.5.0/aoj-cli_0.5.0_Linux_amd64.tar.gz"
      sha256 "a8a77122f136a73d327daf04693ab624a8105778abc78e425e6e5b897624912b"
    end
  end

  def install
    bin.install "aoj"
  end
end
